apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: pc8oxr1wu-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:3b73387e334dc91eed37ffe4dbb60a302adc1fe6@sha256:2d3bd18229d938f5d011fb64f36d6b6845a2e0f48e42b7072db8bfe4e563d7ac
          name: container-image
