apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pc8oxr1wu-go
  janus-idp.io/tekton: pc8oxr1wu-go
  backstage.io/kubernetes-id: pc8oxr1wu-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pc8oxr1wu-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
